// <auto-generated />
using System;
using AndresGuaman_Examen1PROG.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AndresGuaman_Examen1PROG.Migrations
{
    [DbContext(typeof(AndresGuaman_Examen1PROGContext))]
    [Migration("20231025133248_agBaseDatos")]
    partial class agBaseDatos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AndresGuaman_Examen1PROG.Models.AndresGuaman_tabla", b =>
                {
                    b.Property<int>("agEmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("agEmpleadoId"), 1L, 1);

                    b.Property<string>("agCedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("agConNombramiento")
                        .HasColumnType("bit");

                    b.Property<DateTime>("agFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("agNombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("agSalario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("agEmpleadoId");

                    b.ToTable("AndresGuaman_tabla");
                });
#pragma warning restore 612, 618
        }
    }
}
